unit_test_() ->
    [
     ?_assertEqual("<p>=></p>", conv("=>")),
     ?_assertEqual("<p>=&lt;</p>", conv("=<")),
     ?_assertEqual("<p>&lt;=</p>", conv("<=")),
     ?_assertEqual("<p>&lt;></p>", conv("<>")),
     ?_assertEqual("<p>&copy;</p>", conv("&copy;")),
     ?_assertEqual("<div>\nerk\n</div>", conv("<div>\nerk\n</div>")),
     ?_assertEqual("<p>blah &lt;div&gt;erk&lt;/div&gt; blah</p>", conv("blah <div>erk</div> blah")),
%     ?_assertEqual("blah <span>erk</span> blah", conv("blah <span>erk</span> blah")),
%     ?_assertEqual("blah <img src=\"./image.png\"> blah", conv("blah <img src=\"image.png\"> blah")),
%     ?_assertEqual("blah <a href=\"./link\">link</a> blah", conv("blah <a href=\"link\">link</a> blah")),
     ?_assertEqual("<ol>\n<li>should be <em>italic</em></li>\n<li>should be <strong>bold</strong></li>\n<li>should be <strong><em>bold italic</em></strong></li>\n</ol>", conv("\n 1.   should be *italic*\n 2.  should be **bold**\n 3.  should be ***bold italic***")),
     ?_assertEqual("<p>should be <em>italic</em> should be <strong>bold</strong> should be <strong><em>bold italic</em></strong></p>", conv("should be *italic* should be **bold** should be ***bold italic***")),
     ?_assertEqual("<p>some stuff <code>yaycode</code> more stuff <code>more code!</code></p>", conv("some stuff `yaycode` more stuff `more code!`")),
     ?_assertEqual("<pre><code>alice\nbob\n</code></pre>\n\n<p>chaz</p>", conv("    alice\n    bob\nchaz")),
     ?_assertEqual("<ol>\n<li>a</li>\n<li>b</li>\n</ol>", conv(" 1. a\n 2. b\n")),

     ?_assertEqual("<p>Now is the winter of <code>our discontent</code> made glorious summer by this Son of York</p>", conv("Now is the winter of `our discontent` made glorious summer by this Son of York")),

     ?_assertEqual("<p>blah</p>\n<p>bleh</p>", conv("blah\n\n\nbleh")),
     ?_assertEqual("<p><code>&lt;div&gt;blah&lt;/div&gt;</code></p>", conv("`<div>blah</div>`")),
     ?_assertEqual("<p><em>_</em>blah</p>\n<p>a</p>", conv("___blah\na")),
     ?_assertEqual("<p>---blah</p>\n<p>a</p>", conv("---blah\na")),
     ?_assertEqual("<p><em>*</em>blah</p>\n<p>a</p>", conv("***blah\na")),
     ?_assertEqual("<pre><code>&lt;div&gt;&amp;\n</code></pre>", conv("\t<div>&")),
     ?_assertEqual("<pre><code>&lt;div&gt;\n</code></pre>", conv("\t<div>")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", conv("\tb\n\n\n\n\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", conv("\tb\n\n\n\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", conv("\tb\n\n\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", conv("\tb\n\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", conv("\tb\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>", conv("\tb")),
     ?_assertEqual("<pre><code>b\n</code></pre>", conv("    b")),
     ?_assertEqual("<ol>\n<li><p>a</p></li>\n<li><p>b</p></li>\n<li><p>c</p></li>\n</ol>", conv("4. a\n\n5. b\n\n6. c")),
     ?_assertEqual("<ol>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n</ol>", conv("4. a\n5. b\n6. c")),
     ?_assertEqual("<ol>\n<li>blah\nblah</li>\n</ol>", conv("4. blah\nblah")),
     ?_assertEqual("<p>555.blah</p>\n<p>a</p>", conv("555.blah\na")),
     ?_assertEqual("<p>555 @blah</p>\n<p>a</p>", conv("555 @blah\na")),
     ?_assertEqual("<ol>\n<li>blah</li>\n</ol>", conv("555. blah")),
     ?_assertEqual("<ol>\n<li>blah</li>\n</ol>", conv("4. blah")),
     ?_assertEqual("<ol>\n<li>blah</li>\n</ol>", conv("1. blah")),
     ?_assertEqual("<p>*blah</p>\n<p>a</p>", conv("*blah\na")),
     ?_assertEqual("<ul>\n<li>blah</li>\n</ul>", conv("* blah")),
     ?_assertEqual("<h1>blahblah</h1>\n<p>bleh</p>", conv("# blahblah ###\nbleh")),
     ?_assertEqual("<h6># blahblah</h6>\n<p>bleh</p>", conv("####### blahblah\nbleh")),
     ?_assertEqual("<h6>blahblah</h6>\n<p>bleh</p>", conv("###### blahblah\nbleh")),
     ?_assertEqual("<h5>blahblah</h5>\n<p>bleh</p>", conv("##### blahblah\nbleh")),
     ?_assertEqual("<h4>blahblah</h4>\n<p>bleh</p>", conv("#### blahblah\nbleh")),
     ?_assertEqual("<h3>blahblah</h3>\n<p>bleh</p>", conv("### blahblah\nbleh")),
     ?_assertEqual("<h2>blahblah</h2>\n<p>bleh</p>", conv("## blahblah\nbleh")),
     ?_assertEqual("<h1>blahblah</h1>\n<p>bleh</p>", conv("# blahblah\nbleh")),
     ?_assertEqual("<h1>blahblah</h1>", conv("# blahblah ###")),
     ?_assertEqual("<h6># blahblah</h6>", conv("####### blahblah")),
     ?_assertEqual("<h6>blahblah</h6>", conv("###### blahblah")),
     ?_assertEqual("<h5>blahblah</h5>", conv("##### blahblah")),
     ?_assertEqual("<h4>blahblah</h4>", conv("#### blahblah")),
     ?_assertEqual("<h3>blahblah</h3>", conv("### blahblah")),
     ?_assertEqual("<h2>blahblah</h2>", conv("## blahblah")),
     ?_assertEqual("<h1>blahblah</h1>", conv("# blahblah")),
     ?_assertEqual("<p>blah</p>\n<p>blah</p>", conv("blah\r\nblah\n")),
     ?_assertEqual("<p>blah</p>\n<p>blah</p>", conv("blah\r\nblah")),
     ?_assertEqual("<p>blah</p>\n<p>blah</p>", conv("blah\nblah")),
     ?_assertEqual("<p><strong><em>you</em></strong> sad bastard</p>\n<p>a</p>", conv("___you___ sad bastard\na")),
     ?_assertEqual("<p><strong>you</strong> sad bastard</p>\n<p>a</p>", conv("__you__ sad bastard\na")),
     ?_assertEqual("<p><em>you</em> sad bastard</p>\n<p>a</p>", conv("_you_ sad bastard\na")),
     ?_assertEqual("<p><strong><em>you</em></strong> sad bastard</p>\n<p>a</p>", conv("***you*** sad bastard\na")),
     ?_assertEqual("<p><strong>you</strong> sad bastard</p>\n<p>a</p>", conv("**you** sad bastard\na")),
     ?_assertEqual("<p><em>you</em> sad bastard</p>\n<p>a</p>", conv("*you* sad bastard\na")),
     ?_assertEqual("<p>you _sad_ bastard</p>\n<p>a</p>", conv("you \\_sad\\_ bastard\na")),
     ?_assertEqual("<p>you *sad* bastard</p>\n<p>a</p>", conv("you \\*sad\\* bastard\na")),
     ?_assertEqual("<p>you<em>sad</em>bastard</p>\n<p>a</p>", conv("you_sad_bastard\na")),
     ?_assertEqual("<p>you<em>sad</em>bastard</p>\n<p>a</p>", conv("you*sad*bastard\na")),
     ?_assertEqual("<p>you <strong><em>sad</em></strong> bastard</p>\n<p>a</p>", conv("you ___sad___ bastard\na")),
     ?_assertEqual("<p>you <strong>sad</strong> bastard</p>\n<p>a</p>", conv("you __sad__ bastard\na")),
     ?_assertEqual("<p>you <em>sad</em> bastard</p>\n<p>a</p>", conv("you _sad_ bastard\na")),
     ?_assertEqual("<p>you <strong><em>sad</em></strong> bastard</p>\n<p>a</p>", conv("you ***sad*** bastard\na")),
     ?_assertEqual("<p>you <strong>sad</strong> bastard</p>\n<p>a</p>", conv("you **sad** bastard\na")),
     ?_assertEqual("<p>you <em>sad</em> bastard</p>\n<p>a</p>", conv("you *sad* bastard\na")),
     ?_assertEqual("<h6>#</h6>\n<p>a</p>", conv("########\na")),
     ?_assertEqual("<h6>#</h6>\n<p>a</p>", conv("#######\na")),
     ?_assertEqual("<h5>#</h5>\n<p>a</p>", conv("######\na")),
     ?_assertEqual("<h4>#</h4>\n<p>a</p>", conv("#####\na")),
     ?_assertEqual("<h3>#</h3>\n<p>a</p>", conv("####\na")),
     ?_assertEqual("<h2>#</h2>\n<p>a</p>", conv("###\na")),
     ?_assertEqual("<h1>#</h1>\n<p>a</p>", conv("##\na")),
     ?_assertEqual("<p>#</p>\n<p>a</p>", conv("#\na")),
     ?_assertEqual("<p>[</p>\n<p>a</p>", conv("\n[\na")),
     ?_assertEqual("<p>></p>\n<p>a</p>", conv("\n>\na")),
     ?_assertEqual("<p>-</p>\n<p>a</p>", conv("\n-\na")),
     ?_assertEqual("<p>[</p>\n<p>a</p>", conv("[\na")),
     ?_assertEqual("<p>></p>\n<p>a</p>", conv(">\na")),
     ?_assertEqual("<p>-</p>\n<p>a</p>", conv("-\na")),
     ?_assertEqual("<p>abc`def</p>\n<p>a</p>", conv("abc\\`def\na")),
     ?_assertEqual("<p>xyz</p>\n<p>ab:c</p>\n<p>a</p>", conv("xyz\r\nab:c\na")),
     ?_assertEqual("<p>xyz</p>\n<p>ab:c</p>\n<p>a</p>", conv("xyz\nab:c\na")),
     ?_assertEqual("<p>xyz    ab:c</p>\n<p>a</p>", conv("xyz\tab:c\na")),
     ?_assertEqual("<p>xyz ab:c</p>\n<p>a</p>", conv("xyz ab:c\na")),
     ?_assertEqual("<p>xyz(ab:c</p>\n<p>a</p>", conv("xyz(ab:c\na")),
     ?_assertEqual("<p>xyz]ab:c</p>\n<p>a</p>", conv("xyz]ab:c\na")),
     ?_assertEqual("<p>xyz[ab:c</p>\n<p>a</p>", conv("xyz[ab:c\na")),
     ?_assertEqual("<p>xyz)ab:c</p>\n<p>a</p>", conv("xyz)ab:c\na")),
     ?_assertEqual("<p>xyz(ab:c</p>\n<p>a</p>", conv("xyz(ab:c\na")),
     ?_assertEqual("<p>xyz/ab:c</p>\n<p>a</p>", conv("xyz/ab:c\na")),
     ?_assertEqual("<p>xyz\\ab:c</p>\n<p>a</p>", conv("xyz\\ab:c\na")),
     ?_assertEqual("<p>xyz!ab:c</p>\n<p>a</p>", conv("xyz!ab:c\na")),
     ?_assertEqual("<p>xyz`ab:c</p>\n<p>a</p>", conv("xyz`ab:c\na")),
     ?_assertEqual("<p>xyz\"ab:c</p>\n<p>a</p>", conv("xyz\"ab:c\na")),
     ?_assertEqual("<p>xyz'ab:c</p>\n<p>a</p>", conv("xyz'ab:c\na")),
     ?_assertEqual("<p>xyz:ab:c</p>\n<p>a</p>", conv("xyz:ab:c\na")),
     ?_assertEqual("<p>xyz.ab:c</p>\n<p>a</p>", conv("xyz.ab:c\na")),
     ?_assertEqual("<p>xyz0ab:c</p>\n<p>a</p>", conv("xyz0ab:c\na")),
     ?_assertEqual("<p>xyz9ab:c</p>\n<p>a</p>", conv("xyz9ab:c\na")),
     ?_assertEqual("<p>xyz8ab:c</p>\n<p>a</p>", conv("xyz8ab:c\na")),
     ?_assertEqual("<p>xyz7ab:c</p>\n<p>a</p>", conv("xyz7ab:c\na")),
     ?_assertEqual("<p>xyz6ab:c</p>\n<p>a</p>", conv("xyz6ab:c\na")),
     ?_assertEqual("<p>xyz5ab:c</p>\n<p>a</p>", conv("xyz5ab:c\na")),
     ?_assertEqual("<p>xyz4ab:c</p>\n<p>a</p>", conv("xyz4ab:c\na")),
     ?_assertEqual("<p>xyz3ab:c</p>\n<p>a</p>", conv("xyz3ab:c\na")),
     ?_assertEqual("<p>xyz2ab:c</p>\n<p>a</p>", conv("xyz2ab:c\na")),
     ?_assertEqual("<p>xyz1ab:c</p>\n<p>a</p>", conv("xyz1ab:c\na")),
     ?_assertEqual("<p>xyz_ab:c</p>\n<p>a</p>", conv("xyz_ab:c\na")),
     ?_assertEqual("<p>xyz*ab:c</p>\n<p>a</p>", conv("xyz*ab:c\na")),
     ?_assertEqual("<p>xyz+ab:c</p>\n<p>a</p>", conv("xyz+ab:c\na")),
     ?_assertEqual("<p>xyz>ab:c</p>\n<p>a</p>", conv("xyz>ab:c\na")),
     ?_assertEqual("<p>xyz#ab:c</p>\n<p>a</p>", conv("xyz#ab:c\na")),
     ?_assertEqual("<p>xyz-ab:c</p>\n<p>a</p>", conv("xyz-ab:c\na")),
     ?_assertEqual("<p>xyz=ab:c</p>\n<p>a</p>", conv("xyz=ab:c\na")),
     ?_assertEqual("<p>xyz/ab:c</p>\n<p>a</p>", conv("xyz/ab:c\na")),
     ?_assertEqual("<p>ab:c</p>\n<p>a</p>", conv("\r\n ab:c\na")),
     ?_assertEqual("<p>ab:c</p>\n<p>a</p>", conv("\n ab:c\na")),
     ?_assertEqual("<pre><code> ab:c\n</code></pre>\n\n<p>a</p>", conv("\t ab:c\na")),
     ?_assertEqual("<p>ab:c</p>\n<p>a</p>", conv("  ab:c\na")),
     ?_assertEqual("<p>( ab:c</p>\n<p>a</p>", conv("( ab:c\na")),
     ?_assertEqual("<p>] ab:c</p>\n<p>a</p>", conv("] ab:c\na")),
     ?_assertEqual("<p>[ ab:c</p>\n<p>a</p>", conv("[ ab:c\na")),
     ?_assertEqual("<p>) ab:c</p>\n<p>a</p>", conv(") ab:c\na")),
     ?_assertEqual("<p>( ab:c</p>\n<p>a</p>", conv("( ab:c\na")),
     ?_assertEqual("<p>/ ab:c</p>\n<p>a</p>", conv("/ ab:c\na")),
     ?_assertEqual("<p>\\ ab:c</p>\n<p>a</p>", conv("\\ ab:c\na")),
     ?_assertEqual("<p>! ab:c</p>\n<p>a</p>", conv("! ab:c\na")),
     ?_assertEqual("<p>` ab:c</p>\n<p>a</p>", conv("` ab:c\na")),
     ?_assertEqual("<p>\" ab:c</p>\n<p>a</p>", conv("\" ab:c\na")),
     ?_assertEqual("<p>' ab:c</p>\n<p>a</p>", conv("' ab:c\na")),
     ?_assertEqual("<p>: ab:c</p>\n<p>a</p>", conv(": ab:c\na")),
     ?_assertEqual("<p>. ab:c</p>\n<p>a</p>", conv(". ab:c\na")),
     ?_assertEqual("<p>0 ab:c</p>\n<p>a</p>", conv("0 ab:c\na")),
     ?_assertEqual("<p>9 ab:c</p>\n<p>a</p>", conv("9 ab:c\na")),
     ?_assertEqual("<p>8 ab:c</p>\n<p>a</p>", conv("8 ab:c\na")),
     ?_assertEqual("<p>7 ab:c</p>\n<p>a</p>", conv("7 ab:c\na")),
     ?_assertEqual("<p>6 ab:c</p>\n<p>a</p>", conv("6 ab:c\na")),
     ?_assertEqual("<p>5 ab:c</p>\n<p>a</p>", conv("5 ab:c\na")),
     ?_assertEqual("<p>4 ab:c</p>\n<p>a</p>", conv("4 ab:c\na")),
     ?_assertEqual("<p>3 ab:c</p>\n<p>a</p>", conv("3 ab:c\na")),
     ?_assertEqual("<p>2 ab:c</p>\n<p>a</p>", conv("2 ab:c\na")),
     ?_assertEqual("<p>1 ab:c</p>\n<p>a</p>", conv("1 ab:c\na")),
     ?_assertEqual("<p>_ ab:c</p>\n<p>a</p>", conv("_ ab:c\na")),
     ?_assertEqual("<ul>\n<li>ab:c\na</li>\n</ul>", conv("* ab:c\na")),
     ?_assertEqual("<h1>ab:c</h1>\n<p>a</p>", conv("# ab:c\na")),
     ?_assertEqual("<p>= ab:c</p>\n<p>a</p>", conv("= ab:c\na")),
     ?_assertEqual("<p>/ ab:c</p>\n<p>a</p>", conv("/ ab:c\na")),
     ?_assertEqual("<p>&lt; /ab:c</p>\n<p>a</p>", conv("< /ab:c\na")),
     ?_assertEqual("<p>&lt; ab:c</p>\n<p>a</p>", conv("< ab:c\na")),
     ?_assertEqual("<p>ab:c</p>\n<p>a</p>", conv("\r\nab:c\na")),
     ?_assertEqual("<p>ab:c</p>\n<p>a</p>", conv("\nab:c\na")),
     ?_assertEqual("<pre><code>ab:c\n</code></pre>\n\n<p>a</p>", conv("\tab:c\na")),
     ?_assertEqual("<p>ab:c</p>\n<p>a</p>", conv(" ab:c\na")),
     ?_assertEqual("<p>(ab:c</p>\n<p>a</p>", conv("(ab:c\na")),
     ?_assertEqual("<p>]ab:c</p>\n<p>a</p>", conv("]ab:c\na")),
     ?_assertEqual("<p>[ab:c</p>\n<p>a</p>", conv("[ab:c\na")),
     ?_assertEqual("<p>)ab:c</p>\n<p>a</p>", conv(")ab:c\na")),
     ?_assertEqual("<p>(ab:c</p>\n<p>a</p>", conv("(ab:c\na")),
     ?_assertEqual("<p>/ab:c</p>\n<p>a</p>", conv("/ab:c\na")),
     ?_assertEqual("<p>\\ab:c</p>\n<p>a</p>", conv("\\ab:c\na")),
     ?_assertEqual("<p>!ab:c</p>\n<p>a</p>", conv("!ab:c\na")),
     ?_assertEqual("<p>`ab:c</p>\n<p>a</p>", conv("`ab:c\na")),
     ?_assertEqual("<p>\"ab:c</p>\n<p>a</p>", conv("\"ab:c\na")),
     ?_assertEqual("<p>'ab:c</p>\n<p>a</p>", conv("'ab:c\na")),
     ?_assertEqual("<p>:ab:c</p>\n<p>a</p>", conv(":ab:c\na")),
     ?_assertEqual("<p>.ab:c</p>\n<p>a</p>", conv(".ab:c\na")),
     ?_assertEqual("<p>0ab:c</p>\n<p>a</p>", conv("0ab:c\na")),
     ?_assertEqual("<p>9ab:c</p>\n<p>a</p>", conv("9ab:c\na")),
     ?_assertEqual("<p>8ab:c</p>\n<p>a</p>", conv("8ab:c\na")),
     ?_assertEqual("<p>7ab:c</p>\n<p>a</p>", conv("7ab:c\na")),
     ?_assertEqual("<p>6ab:c</p>\n<p>a</p>", conv("6ab:c\na")),
     ?_assertEqual("<p>5ab:c</p>\n<p>a</p>", conv("5ab:c\na")),
     ?_assertEqual("<p>4ab:c</p>\n<p>a</p>", conv("4ab:c\na")),
     ?_assertEqual("<p>3ab:c</p>\n<p>a</p>", conv("3ab:c\na")),
     ?_assertEqual("<p>2ab:c</p>\n<p>a</p>", conv("2ab:c\na")),
     ?_assertEqual("<p>1ab:c</p>\n<p>a</p>", conv("1ab:c\na")),
     ?_assertEqual("<p>_ab:c</p>\n<p>a</p>", conv("_ab:c\na")),
     ?_assertEqual("<p>*ab:c</p>\n<p>a</p>", conv("*ab:c\na")),
     ?_assertEqual("<p>+ab:c</p>\n<p>a</p>", conv("+ab:c\na")),
     ?_assertEqual("<h1>ab:c</h1>\n<p>a</p>", conv("#ab:c\na")),
     ?_assertEqual("<p>-ab:c</p>\n<p>a</p>", conv("-ab:c\na")),
     ?_assertEqual("<p>=ab:c</p>\n<p>a</p>", conv("=ab:c\na")),
     ?_assertEqual("<p>/ab:c</p>\n<p>a</p>", conv("/ab:c\na")),
     ?_assertEqual("<p>Hey</p>\n<p>Ho!</p>\n<p>Lets Go</p>", conv("    \nHey\nHo!  \nLets Go")),
     ?_assertEqual("<p>Hey Ho</p>\n<p>Lets Go</p>", conv("Hey Ho\t\nLets Go")),
     ?_assertEqual("<p>Hey Ho</p>\n<p>Lets Go</p>", conv("Hey Ho  \nLets Go")),
     ?_assertEqual("<p>Hey</p>\n<p>Ho!</p>\n<p>Hardy</p>", conv("Hey\nHo!\nHardy\n\n")),
     ?_assertEqual("<p>Hey Ho!</p>\n<p>a</p>", conv("Hey Ho!\na")),
     ?_assertEqual("<p>3 &lt;4</p>\n<p>a</p>", conv(" 3 <4\na")),
     ?_assertEqual("<p>3 &lt; 4</p>\n<p>a</p>", conv(" 3 < 4\na")),
     ?_assertEqual("<p>3 > 4</p>\n<p>a</p>", conv("3 > 4\na")),
     ?_assertEqual("<p>a</p>\n<p>b</p>\n<p>c</p>", conv("a\nb\nc\n \n\t\n     ")),
     ?_assertEqual("<p>a</p>\n<p>b</p>\n<p>c</p>", conv("a\nb\nc\n\n\n")),
     ?_assertEqual("", conv("  \n")),
     ?_assertEqual("", conv("\t\n")),
     ?_assertEqual("", conv("\n\n")),
     ?_assertEqual("", conv("\n"))
    ].
